--- #YAML:1.0
name:               POSIX-bsearch
version:            0.02
abstract:           supplies (and extends) a function missing from the L<POSIX> module
author:
    - A. U. Thor <david@localdomain>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
